### ISSUE TITLE
Content is barely visible

### ISSUE THREAD

**Issue by fakela** [calimero-is-near/docs#14]
Hi @chefsale I was checking the docs and I can barely the content
<img width="1507" alt="Screenshot 2023-01-27 at 16 17 07" src="https://user-images.githubusercontent.com/39309699/215121693-ee47d0dd-afc8-4793-b295-abdaa0eef8c6.png">

**Comment by chefsale** [comment]
Weird, can you try to restart the browser and delete the cache?

**Comment by chefsale** [comment]
I was able to reproduce it, will fix it now. Thanks.

**Comment by chefsale** [comment]
@fakela could you share the browser and operating system you are using?

**Comment by fakela** [comment]
I'm using a  Mac OS X and chrome browser
<img width="1489" alt="Screenshot 2023-01-27 at 17 42 44" src="https://user-images.githubusercontent.com/39309699/215143850-774ede7e-d5c0-4606-8d49-cf632fe49192.png">

so the color is back on the content but the side navbar still needs color
